// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public final class Any extends
    com.google.protobuf.nano.MessageNano {

  private static volatile Any[] _emptyArray;
  public static Any[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new Any[0];
        }
      }
    }
    return _emptyArray;
  }

  private int bitField0_;

  // optional string type_url = 1;
  private String typeUrl_;
  public String getTypeUrl() {
    return typeUrl_;
  }
  public Any setTypeUrl(String value) {
    if (value == null) {
      throw new NullPointerException();
    }
    typeUrl_ = value;
    bitField0_ |= 0x00000001;
    return this;
  }
  public boolean hasTypeUrl() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  public Any clearTypeUrl() {
    typeUrl_ = "";
    bitField0_ = (bitField0_ & ~0x00000001);
    return this;
  }

  // optional bytes value = 2;
  private byte[] value_;
  public byte[] getValue() {
    return value_;
  }
  public Any setValue(byte[] value) {
    if (value == null) {
      throw new NullPointerException();
    }
    value_ = value;
    bitField0_ |= 0x00000002;
    return this;
  }
  public boolean hasValue() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  public Any clearValue() {
    value_ = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    bitField0_ = (bitField0_ & ~0x00000002);
    return this;
  }

  public Any() {
    clear();
  }

  public Any clear() {
    bitField0_ = 0;
    typeUrl_ = "";
    value_ = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeString(1, typeUrl_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, value_);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, typeUrl_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(2, value_);
    }
    return size;
  }

  @Override
  public Any mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          typeUrl_ = input.readString();
          bitField0_ |= 0x00000001;
          break;
        }
        case 18: {
          value_ = input.readBytes();
          bitField0_ |= 0x00000002;
          break;
        }
      }
    }
  }

  public static Any parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new Any(), data);
  }

  public static Any parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new Any().mergeFrom(input);
  }
}
