// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public interface CodeListUpdateRequest {

  public static final class CodeListUpdate_Request extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CodeListUpdate_Request[] _emptyArray;
    public static CodeListUpdate_Request[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CodeListUpdate_Request[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional uint32 last_version = 1;
    private int lastVersion_;
    public int getLastVersion() {
      return lastVersion_;
    }
    public CodeListUpdate_Request setLastVersion(int value) {
      lastVersion_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasLastVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CodeListUpdate_Request clearLastVersion() {
      lastVersion_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional uint32 size_limit = 2;
    private int sizeLimit_;
    public int getSizeLimit() {
      return sizeLimit_;
    }
    public CodeListUpdate_Request setSizeLimit(int value) {
      sizeLimit_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasSizeLimit() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public CodeListUpdate_Request clearSizeLimit() {
      sizeLimit_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public CodeListUpdate_Request() {
      clear();
    }

    public CodeListUpdate_Request clear() {
      bitField0_ = 0;
      lastVersion_ = 0;
      sizeLimit_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, lastVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, sizeLimit_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, lastVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, sizeLimit_);
      }
      return size;
    }

    @Override
    public CodeListUpdate_Request mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            lastVersion_ = input.readUInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            sizeLimit_ = input.readUInt32();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static CodeListUpdate_Request parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CodeListUpdate_Request(), data);
    }

    public static CodeListUpdate_Request parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CodeListUpdate_Request().mergeFrom(input);
    }
  }
}
