// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public interface RankListResponse {

  public static final class RankList_Response extends
      com.google.protobuf.nano.MessageNano {

    public static final class Response extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Response[] _emptyArray;
      public static Response[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Response[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional string template_name = 1;
      private String templateName_;
      public String getTemplateName() {
        return templateName_;
      }
      public Response setTemplateName(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        templateName_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasTemplateName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public Response clearTemplateName() {
        templateName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional .SortedList_Response template_rank_response = 2;
      public SortedListResponse.SortedList_Response templateRankResponse;

      public Response() {
        clear();
      }

      public Response clear() {
        bitField0_ = 0;
        templateName_ = "";
        templateRankResponse = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeString(1, templateName_);
        }
        if (this.templateRankResponse != null) {
          output.writeMessage(2, this.templateRankResponse);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, templateName_);
        }
        if (this.templateRankResponse != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.templateRankResponse);
        }
        return size;
      }

      @Override
      public Response mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              templateName_ = input.readString();
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (this.templateRankResponse == null) {
                this.templateRankResponse = new SortedListResponse.SortedList_Response();
              }
              input.readMessage(this.templateRankResponse);
              break;
            }
          }
        }
      }

      public static Response parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Response(), data);
      }

      public static Response parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Response().mergeFrom(input);
      }
    }

    private static volatile RankList_Response[] _emptyArray;
    public static RankList_Response[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RankList_Response[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .RankList_Response.Response rank_list_response = 1;
    public Response[] rankListResponse;

    public RankList_Response() {
      clear();
    }

    public RankList_Response clear() {
      rankListResponse = Response.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rankListResponse != null && this.rankListResponse.length > 0) {
        for (int i = 0; i < this.rankListResponse.length; i++) {
          Response element = this.rankListResponse[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rankListResponse != null && this.rankListResponse.length > 0) {
        for (int i = 0; i < this.rankListResponse.length; i++) {
          Response element = this.rankListResponse[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public RankList_Response mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rankListResponse == null ? 0 : this.rankListResponse.length;
            Response[] newArray =
                new Response[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.rankListResponse, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new Response();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new Response();
            input.readMessage(newArray[i]);
            this.rankListResponse = newArray;
            break;
          }
        }
      }
    }

    public static RankList_Response parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RankList_Response(), data);
    }

    public static RankList_Response parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RankList_Response().mergeFrom(input);
    }
  }
}
