// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public interface RankListRequest {

  public static final class RankList_Request extends
      com.google.protobuf.nano.MessageNano {

    public static final class Request extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Request[] _emptyArray;
      public static Request[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Request[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional string template_name = 1;
      private String templateName_;
      public String getTemplateName() {
        return templateName_;
      }
      public Request setTemplateName(String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        templateName_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasTemplateName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public Request clearTemplateName() {
        templateName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional .SortedList_Request template_rank_request = 2;
      public SortedListRequest.SortedList_Request templateRankRequest;

      public Request() {
        clear();
      }

      public Request clear() {
        bitField0_ = 0;
        templateName_ = "";
        templateRankRequest = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeString(1, templateName_);
        }
        if (this.templateRankRequest != null) {
          output.writeMessage(2, this.templateRankRequest);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, templateName_);
        }
        if (this.templateRankRequest != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.templateRankRequest);
        }
        return size;
      }

      @Override
      public Request mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              templateName_ = input.readString();
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (this.templateRankRequest == null) {
                this.templateRankRequest = new SortedListRequest.SortedList_Request();
              }
              input.readMessage(this.templateRankRequest);
              break;
            }
          }
        }
      }

      public static Request parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Request(), data);
      }

      public static Request parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Request().mergeFrom(input);
      }
    }

    private static volatile RankList_Request[] _emptyArray;
    public static RankList_Request[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RankList_Request[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .RankList_Request.Request rank_list_request = 1;
    public Request[] rankListRequest;

    public RankList_Request() {
      clear();
    }

    public RankList_Request clear() {
      rankListRequest = Request.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rankListRequest != null && this.rankListRequest.length > 0) {
        for (int i = 0; i < this.rankListRequest.length; i++) {
          Request element = this.rankListRequest[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rankListRequest != null && this.rankListRequest.length > 0) {
        for (int i = 0; i < this.rankListRequest.length; i++) {
          Request element = this.rankListRequest[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public RankList_Request mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rankListRequest == null ? 0 : this.rankListRequest.length;
            Request[] newArray =
                new Request[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.rankListRequest, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new Request();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new Request();
            input.readMessage(newArray[i]);
            this.rankListRequest = newArray;
            break;
          }
        }
      }
    }

    public static RankList_Request parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RankList_Request(), data);
    }

    public static RankList_Request parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RankList_Request().mergeFrom(input);
    }
  }
}
