// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public interface SortedListRequest {

  public static final class SortedList_Request extends
      com.google.protobuf.nano.MessageNano {

    public static final class ClassTypeList extends
        com.google.protobuf.nano.MessageNano {

      public static final class ClassType extends
          com.google.protobuf.nano.MessageNano {

        private static volatile ClassType[] _emptyArray;
        public static ClassType[] emptyArray() {
          // Lazily initializes the empty array
          if (_emptyArray == null) {
            synchronized (
                com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
              if (_emptyArray == null) {
                _emptyArray = new ClassType[0];
              }
            }
          }
          return _emptyArray;
        }

        private int bitField0_;

        // optional uint32 exchange = 5;
        private int exchange_;
        public int getExchange() {
          return exchange_;
        }
        public ClassType setExchange(int value) {
          exchange_ = value;
          bitField0_ |= 0x00000001;
          return this;
        }
        public boolean hasExchange() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        public ClassType clearExchange() {
          exchange_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        // optional uint64 category = 6;
        private long category_;
        public long getCategory() {
          return category_;
        }
        public ClassType setCategory(long value) {
          category_ = value;
          bitField0_ |= 0x00000002;
          return this;
        }
        public boolean hasCategory() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        public ClassType clearCategory() {
          category_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public ClassType() {
          clear();
        }

        public ClassType clear() {
          bitField0_ = 0;
          exchange_ = 0;
          category_ = 0L;
          cachedSize = -1;
          return this;
        }

        @Override
        public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
            throws java.io.IOException {
          if (((bitField0_ & 0x00000001) != 0)) {
            output.writeUInt32(5, exchange_);
          }
          if (((bitField0_ & 0x00000002) != 0)) {
            output.writeUInt64(6, category_);
          }
          super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
          int size = super.computeSerializedSize();
          if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeUInt32Size(5, exchange_);
          }
          if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeUInt64Size(6, category_);
          }
          return size;
        }

        @Override
        public ClassType mergeFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                return this;
              default: {
                if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                  return this;
                }
                break;
              }
              case 40: {
                exchange_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              }
              case 48: {
                category_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        }

        public static ClassType parseFrom(byte[] data)
            throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
          return com.google.protobuf.nano.MessageNano.mergeFrom(new ClassType(), data);
        }

        public static ClassType parseFrom(
                com.google.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          return new ClassType().mergeFrom(input);
        }
      }

      private static volatile ClassTypeList[] _emptyArray;
      public static ClassTypeList[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ClassTypeList[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .SortedList_Request.ClassTypeList.ClassType exchange_category = 1;
      public ClassType[] exchangeCategory;

      public ClassTypeList() {
        clear();
      }

      public ClassTypeList clear() {
        exchangeCategory = ClassType.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.exchangeCategory != null && this.exchangeCategory.length > 0) {
          for (int i = 0; i < this.exchangeCategory.length; i++) {
            ClassType element = this.exchangeCategory[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.exchangeCategory != null && this.exchangeCategory.length > 0) {
          for (int i = 0; i < this.exchangeCategory.length; i++) {
            ClassType element = this.exchangeCategory[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        return size;
      }

      @Override
      public ClassTypeList mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.exchangeCategory == null ? 0 : this.exchangeCategory.length;
              ClassType[] newArray =
                  new ClassType[i + arrayLength];
              if (i != 0) {
                System.arraycopy(this.exchangeCategory, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new ClassType();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new ClassType();
              input.readMessage(newArray[i]);
              this.exchangeCategory = newArray;
              break;
            }
          }
        }
      }

      public static ClassTypeList parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new ClassTypeList(), data);
      }

      public static ClassTypeList parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ClassTypeList().mergeFrom(input);
      }
    }

    public static final class GoodsList extends
        com.google.protobuf.nano.MessageNano {

      private static volatile GoodsList[] _emptyArray;
      public static GoodsList[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new GoodsList[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated uint32 goods_id = 1;
      public int[] goodsId;

      public GoodsList() {
        clear();
      }

      public GoodsList clear() {
        goodsId = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.goodsId != null && this.goodsId.length > 0) {
          for (int i = 0; i < this.goodsId.length; i++) {
            output.writeUInt32(1, this.goodsId[i]);
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.goodsId != null && this.goodsId.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.goodsId.length; i++) {
            int element = this.goodsId[i];
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeUInt32SizeNoTag(element);
          }
          size += dataSize;
          size += 1 * this.goodsId.length;
        }
        return size;
      }

      @Override
      public GoodsList mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 8);
              int i = this.goodsId == null ? 0 : this.goodsId.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                System.arraycopy(this.goodsId, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readUInt32();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readUInt32();
              this.goodsId = newArray;
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              // First pass to compute array length.
              int arrayLength = 0;
              int startPos = input.getPosition();
              while (input.getBytesUntilLimit() > 0) {
                input.readUInt32();
                arrayLength++;
              }
              input.rewindToPosition(startPos);
              int i = this.goodsId == null ? 0 : this.goodsId.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                System.arraycopy(this.goodsId, 0, newArray, 0, i);
              }
              for (; i < newArray.length; i++) {
                newArray[i] = input.readUInt32();
              }
              this.goodsId = newArray;
              input.popLimit(limit);
              break;
            }
          }
        }
      }

      public static GoodsList parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new GoodsList(), data);
      }

      public static GoodsList parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new GoodsList().mergeFrom(input);
      }
    }

    public static final class GroupInfo extends
        com.google.protobuf.nano.MessageNano {

      private static volatile GroupInfo[] _emptyArray;
      public static GroupInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new GroupInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional uint32 goods_id = 1;
      private int goodsId_;
      public int getGoodsId() {
        return goodsId_;
      }
      public GroupInfo setGoodsId(int value) {
        goodsId_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public GroupInfo clearGoodsId() {
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional uint32 group_type = 2;
      private int groupType_;
      public int getGroupType() {
        return groupType_;
      }
      public GroupInfo setGroupType(int value) {
        groupType_ = value;
        bitField0_ |= 0x00000002;
        return this;
      }
      public boolean hasGroupType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      public GroupInfo clearGroupType() {
        groupType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public GroupInfo() {
        clear();
      }

      public GroupInfo clear() {
        bitField0_ = 0;
        goodsId_ = 0;
        groupType_ = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeUInt32(1, goodsId_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeUInt32(2, groupType_);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(1, goodsId_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(2, groupType_);
        }
        return size;
      }

      @Override
      public GroupInfo mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              goodsId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              groupType_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      }

      public static GroupInfo parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new GroupInfo(), data);
      }

      public static GroupInfo parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new GroupInfo().mergeFrom(input);
      }
    }

    public static final class SortOptions extends
        com.google.protobuf.nano.MessageNano {

      private static volatile SortOptions[] _emptyArray;
      public static SortOptions[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new SortOptions[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional int32 sort_field = 1;
      private int sortField_;
      public int getSortField() {
        return sortField_;
      }
      public SortOptions setSortField(int value) {
        sortField_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasSortField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public SortOptions clearSortField() {
        sortField_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional bool sort_asce = 2;
      private boolean sortAsce_;
      public boolean getSortAsce() {
        return sortAsce_;
      }
      public SortOptions setSortAsce(boolean value) {
        sortAsce_ = value;
        bitField0_ |= 0x00000002;
        return this;
      }
      public boolean hasSortAsce() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      public SortOptions clearSortAsce() {
        sortAsce_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public SortOptions() {
        clear();
      }

      public SortOptions clear() {
        bitField0_ = 0;
        sortField_ = 0;
        sortAsce_ = false;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, sortField_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBool(2, sortAsce_);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, sortField_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(2, sortAsce_);
        }
        return size;
      }

      @Override
      public SortOptions mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              sortField_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              sortAsce_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      }

      public static SortOptions parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new SortOptions(), data);
      }

      public static SortOptions parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new SortOptions().mergeFrom(input);
      }
    }
    public static final int SYSTEM_FIELD_NUMBER = 1;
    public static final int CUSTOM_FIELD_NUMBER = 2;
    public static final int GOODS_FIELD_NUMBER = 3;
    public static final int GROUP_FIELD_NUMBER = 4;
    private int requestTypeCase_ = 0;
    private Object requestType_;
    public int getRequestTypeCase() {
      return this.requestTypeCase_;
    }
    public SortedList_Request clearRequestType() {
      this.requestTypeCase_ = 0;
      this.requestType_ = null;
      return this;
    }

    private static volatile SortedList_Request[] _emptyArray;
    public static SortedList_Request[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SortedList_Request[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .SortedList_Request.ClassTypeList system = 1;
    public boolean hasSystem() {
      return this.requestTypeCase_ == 1;
    }
    public ClassTypeList getSystem() {
      if (this.requestTypeCase_ == 1) {
        return (ClassTypeList) this.requestType_;
      }
      return null;
    }
    public SortedList_Request setSystem(ClassTypeList value) {
      if (value == null) { throw new NullPointerException(); }
      this.requestTypeCase_ = 1;
      this.requestType_ = value;
      return this;
    }

    // optional .SortedList_Request.GoodsList custom = 2;
    public boolean hasCustom() {
      return this.requestTypeCase_ == 2;
    }
    public GoodsList getCustom() {
      if (this.requestTypeCase_ == 2) {
        return (GoodsList) this.requestType_;
      }
      return null;
    }
    public SortedList_Request setCustom(GoodsList value) {
      if (value == null) { throw new NullPointerException(); }
      this.requestTypeCase_ = 2;
      this.requestType_ = value;
      return this;
    }

    // optional uint32 goods = 3;
    public boolean hasGoods() {
      return this.requestTypeCase_ == 3;
    }
    public int getGoods() {
      if (this.requestTypeCase_ == 3) {
        return (int) (Integer) this.requestType_;
      }
      return 0;
    }
    public SortedList_Request setGoods(int value) {
      this.requestTypeCase_ = 3;
      this.requestType_ = value;
      return this;
    }

    // optional .SortedList_Request.GroupInfo group = 4;
    public boolean hasGroup() {
      return this.requestTypeCase_ == 4;
    }
    public GroupInfo getGroup() {
      if (this.requestTypeCase_ == 4) {
        return (GroupInfo) this.requestType_;
      }
      return null;
    }
    public SortedList_Request setGroup(GroupInfo value) {
      if (value == null) { throw new NullPointerException(); }
      this.requestTypeCase_ = 4;
      this.requestType_ = value;
      return this;
    }

    // repeated int32 fields_id = 5;
    public int[] fieldsId;

    // optional .SortedList_Request.SortOptions sort_option = 6;
    public SortOptions sortOption;

    // optional uint32 begin_position = 7;
    private int beginPosition_;
    public int getBeginPosition() {
      return beginPosition_;
    }
    public SortedList_Request setBeginPosition(int value) {
      beginPosition_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasBeginPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public SortedList_Request clearBeginPosition() {
      beginPosition_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional uint32 limit_size = 8;
    private int limitSize_;
    public int getLimitSize() {
      return limitSize_;
    }
    public SortedList_Request setLimitSize(int value) {
      limitSize_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasLimitSize() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public SortedList_Request clearLimitSize() {
      limitSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public SortedList_Request() {
      clear();
    }

    public SortedList_Request clear() {
      bitField0_ = 0;
      fieldsId = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      sortOption = null;
      beginPosition_ = 0;
      limitSize_ = 0;
      clearRequestType();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.requestTypeCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.requestTypeCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.requestTypeCase_ == 3) {
        output.writeUInt32(
            3, (Integer) this.requestType_);
      }
      if (this.requestTypeCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.fieldsId != null && this.fieldsId.length > 0) {
        for (int i = 0; i < this.fieldsId.length; i++) {
          output.writeInt32(5, this.fieldsId[i]);
        }
      }
      if (this.sortOption != null) {
        output.writeMessage(6, this.sortOption);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(7, beginPosition_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(8, limitSize_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.requestTypeCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.requestTypeCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.requestTypeCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(
                3, (Integer) this.requestType_);
      }
      if (this.requestTypeCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.requestType_);
      }
      if (this.fieldsId != null && this.fieldsId.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.fieldsId.length; i++) {
          int element = this.fieldsId[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.fieldsId.length;
      }
      if (this.sortOption != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.sortOption);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, beginPosition_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(8, limitSize_);
      }
      return size;
    }

    @Override
    public SortedList_Request mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.requestTypeCase_ == 1)) {
              this.requestType_ = new ClassTypeList();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.requestType_);
            this.requestTypeCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.requestTypeCase_ == 2)) {
              this.requestType_ = new GoodsList();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.requestType_);
            this.requestTypeCase_ = 2;
            break;
          }
          case 24: {
            this.requestType_ = input.readUInt32();
            this.requestTypeCase_ = 3;
            break;
          }
          case 34: {
            if (!(this.requestTypeCase_ == 4)) {
              this.requestType_ = new GroupInfo();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.requestType_);
            this.requestTypeCase_ = 4;
            break;
          }
          case 40: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 40);
            int i = this.fieldsId == null ? 0 : this.fieldsId.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.fieldsId, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.fieldsId = newArray;
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.fieldsId == null ? 0 : this.fieldsId.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.fieldsId, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.fieldsId = newArray;
            input.popLimit(limit);
            break;
          }
          case 50: {
            if (this.sortOption == null) {
              this.sortOption = new SortOptions();
            }
            input.readMessage(this.sortOption);
            break;
          }
          case 56: {
            beginPosition_ = input.readUInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 64: {
            limitSize_ = input.readUInt32();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static SortedList_Request parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SortedList_Request(), data);
    }

    public static SortedList_Request parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SortedList_Request().mergeFrom(input);
    }
  }
}
