// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.wjf.approomorm.nano;

@SuppressWarnings("hiding")
public interface SortedListResponse {

  public static final class SortedList_Response extends
      com.google.protobuf.nano.MessageNano {

    public static final class ValueData extends
        com.google.protobuf.nano.MessageNano {

      private static volatile ValueData[] _emptyArray;
      public static ValueData[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ValueData[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional uint32 goods_Id = 1;
      private int goodsId_;
      public int getGoodsId() {
        return goodsId_;
      }
      public ValueData setGoodsId(int value) {
        goodsId_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public ValueData clearGoodsId() {
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // repeated string field_value = 2;
      public String[] fieldValue;

      // optional uint32 exchange = 3;
      private int exchange_;
      public int getExchange() {
        return exchange_;
      }
      public ValueData setExchange(int value) {
        exchange_ = value;
        bitField0_ |= 0x00000002;
        return this;
      }
      public boolean hasExchange() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      public ValueData clearExchange() {
        exchange_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional uint64 category = 4;
      private long category_;
      public long getCategory() {
        return category_;
      }
      public ValueData setCategory(long value) {
        category_ = value;
        bitField0_ |= 0x00000004;
        return this;
      }
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      public ValueData clearCategory() {
        category_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      // optional uint32 trade_session = 5;
      private int tradeSession_;
      public int getTradeSession() {
        return tradeSession_;
      }
      public ValueData setTradeSession(int value) {
        tradeSession_ = value;
        bitField0_ |= 0x00000008;
        return this;
      }
      public boolean hasTradeSession() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      public ValueData clearTradeSession() {
        tradeSession_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public ValueData() {
        clear();
      }

      public ValueData clear() {
        bitField0_ = 0;
        goodsId_ = 0;
        fieldValue = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
        exchange_ = 0;
        category_ = 0L;
        tradeSession_ = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeUInt32(1, goodsId_);
        }
        if (this.fieldValue != null && this.fieldValue.length > 0) {
          for (int i = 0; i < this.fieldValue.length; i++) {
            String element = this.fieldValue[i];
            if (element != null) {
              output.writeString(2, element);
            }
          }
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeUInt32(3, exchange_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeUInt64(4, category_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeUInt32(5, tradeSession_);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(1, goodsId_);
        }
        if (this.fieldValue != null && this.fieldValue.length > 0) {
          int dataCount = 0;
          int dataSize = 0;
          for (int i = 0; i < this.fieldValue.length; i++) {
            String element = this.fieldValue[i];
            if (element != null) {
              dataCount++;
              dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                  .computeStringSizeNoTag(element);
            }
          }
          size += dataSize;
          size += 1 * dataCount;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(3, exchange_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(4, category_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(5, tradeSession_);
        }
        return size;
      }

      @Override
      public ValueData mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              goodsId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 18);
              int i = this.fieldValue == null ? 0 : this.fieldValue.length;
              String[] newArray = new String[i + arrayLength];
              if (i != 0) {
                System.arraycopy(this.fieldValue, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readString();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readString();
              this.fieldValue = newArray;
              break;
            }
            case 24: {
              exchange_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            }
            case 32: {
              category_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            }
            case 40: {
              tradeSession_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      }

      public static ValueData parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new ValueData(), data);
      }

      public static ValueData parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ValueData().mergeFrom(input);
      }
    }

    private static volatile SortedList_Response[] _emptyArray;
    public static SortedList_Response[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SortedList_Response[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .SortedList_Request request_params = 1;
    public SortedListRequest.SortedList_Request requestParams;

    // repeated .SortedList_Response.ValueData value_list = 2;
    public ValueData[] valueList;

    // optional uint32 total_size = 3;
    private int totalSize_;
    public int getTotalSize() {
      return totalSize_;
    }
    public SortedList_Response setTotalSize(int value) {
      totalSize_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public SortedList_Response clearTotalSize() {
      totalSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public SortedList_Response() {
      clear();
    }

    public SortedList_Response clear() {
      bitField0_ = 0;
      requestParams = null;
      valueList = ValueData.emptyArray();
      totalSize_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.requestParams != null) {
        output.writeMessage(1, this.requestParams);
      }
      if (this.valueList != null && this.valueList.length > 0) {
        for (int i = 0; i < this.valueList.length; i++) {
          ValueData element = this.valueList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(3, totalSize_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.requestParams != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.requestParams);
      }
      if (this.valueList != null && this.valueList.length > 0) {
        for (int i = 0; i < this.valueList.length; i++) {
          ValueData element = this.valueList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, totalSize_);
      }
      return size;
    }

    @Override
    public SortedList_Response mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.requestParams == null) {
              this.requestParams = new SortedListRequest.SortedList_Request();
            }
            input.readMessage(this.requestParams);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.valueList == null ? 0 : this.valueList.length;
            ValueData[] newArray =
                new ValueData[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.valueList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new ValueData();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new ValueData();
            input.readMessage(newArray[i]);
            this.valueList = newArray;
            break;
          }
          case 24: {
            totalSize_ = input.readUInt32();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static SortedList_Response parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SortedList_Response(), data);
    }

    public static SortedList_Response parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SortedList_Response().mergeFrom(input);
    }
  }
}
